// Generated by CoffeeScript 1.6.1
(function() {

  $(function() {
    $.get('reg.txt', function(data) {
      var arr_reg, arr_temp, reg, _i, _len;
      arr_reg = [];
      arr_temp = data.split("\n");
      for (_i = 0, _len = arr_temp.length; _i < _len; _i++) {
        reg = arr_temp[_i];
        if (reg !== '') {
          arr_reg.push(reg.split('|')[0]);
        }
      }
      return $('.reg-btn').each(function() {
        if (arr_reg.indexOf($(this).attr('href').substr(1)) !== -1) {
          return $(this).attr({
            href: '#inline_already'
          }).removeClass('markAsGifted').addClass('alreadyGifted').text('已被选定');
        } else {
          return $(this).removeClass('alreadyGifted').addClass('markAsGifted').text('标记选定');
        }
      });
    });
    return $(document).on("submit", ".reg-form", function(event) {
      var regItem, regName;
      regItem = $(this).attr('rel');
      regName = $('.inputtext', this).val();
      if (regName === '') {
        $('.inputtext', this).addClass('error');
        return false;
      }
      $.ajax({
        type: "POST",
        dataType: "json",
        data: {
          'item': regItem,
          'name': regName
        },
        url: "reg.php",
        beforeSend: function() {
          return $(':submit', this).prop('disabled', true);
        },
        complete: function() {
          $("a[href='#" + regItem + "']").attr({
            href: '#inline_already'
          }).removeClass('markAsGifted').addClass('alreadyGifted').text('已被选定');
          $.prettyPhoto.close();
        }
      });
      return false;
    });
  });

}).call(this);
